#FROM node:alpine
FROM node:14.16.1 AS node_base

RUN node --version
RUN npm --version

ENV HOST="0.0.0.0"

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    net-tools curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


COPY naya-web /opt/naya-web
WORKDIR /opt/naya-web

RUN npm install --production

ENV NODE_OPTIONS="--max-old-space-size=8192"
RUN npm run build
EXPOSE 3000

# start app
CMD ["npm", "run", "start"]
